# Generated by Django 4.2.4 on 2023-08-15 18:28

from django.db import migrations
from django.db.migrations import RunPython
from faker import Faker


def create_random_names(apps, schema_editor):
    Name = apps.get_model('first_steps', 'Name')
    fake = Faker()
    for _ in range(100):
        Name.objects.create(name=fake.name())


class Migration(migrations.Migration):

    dependencies = [
        ('first_steps', '0001_initial'),
    ]

    operations = [
        RunPython(create_random_names, lambda x, y: None),
    ]
